SET(CPP_FILES
  Common/vtkVolumeProperties.cxx
  Common/vtkSurfaceBase.cxx
  Common/vtkSurface.cxx
  Common/vtkSMFReader.cxx
  Common/vtkRandomTriangulation.cxx
  Common/vtkQuadricTools.cxx
  Common/vtkOFFWriter.cxx
  Common/vtkOFFReader.cxx
  Common/vtkNeighbourhoodComputation.cxx
  Common/vtkMyMinimalStandardRandomSequence.cxx
  Common/vtkDualMeshDisplay.cxx
  Common/vtkDelaunay.cxx
  Common/vtkCurvatureMeasure.cxx
  Common/vtk2ply.cxx
  Common/viewer2.cxx
  Common/viewer.cxx
  Common/stl2ply.cxx
  Common/RenderWindow.cxx
  Common/RandomTriangulation.cxx
  Common/mesh2vtk.cxx
  Common/ExamplevtkSurface.cxx
  Common/CleanMesh.cxx
  Common/CheckOrientation.cxx
  DiscreteRemeshing/xmlParser.cpp
  DiscreteRemeshing/vtkTestUniformClustering.cxx
  DiscreteRemeshing/vtkManifoldSimplification.cxx
  DiscreteRemeshing/VolumeAnalysis.cxx
  DiscreteRemeshing/ManifoldSimplification.cxx
  DiscreteRemeshing/AnisotropicRemeshing.cxx
  DiscreteRemeshing/AnisotropicRemeshingQ.cxx
  DiscreteRemeshing/ACVD.cxx
  DiscreteRemeshing/ACVDQ.cxx
  VolumeProcessing/vtkOOCMetaImageReader.cxx
  VolumeProcessing/vtkMHDFileWriter.cxx
  VolumeProcessing/vtkImageDataCleanLabels.cxx
  VolumeProcessing/VolumeSubsample.cxx
  VolumeProcessing/VolumeSlice.cxx
  VolumeProcessing/VolumeMedian.cxx
  VolumeProcessing/VolumeCrop.cxx
  VolumeProcessing/VolumeCleanLabels.cxx
  VolumeProcessing/VolumeAnisotropicDiffusion.cxx
  VolumeProcessing/ResampledVolumeGenerator.cxx
  VolumeProcessing/ReadImage.cxx
  VolumeProcessing/png2raw.cxx
  VolumeProcessing/OOCRead.cxx
  VolumeProcessing/Minc2Mhd.cxx
  VolumeProcessing/BinarySubimageWriter.cxx
)